services:
  app:
    build: .
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"  # Laravel app port
      - "5173:5173"  # Vite dev server port
    depends_on:
      - redis
      - db
    networks:
      - app-network
    restart: always
    command: sh -c "pnpm dev & php artisan serve --host=0.0.0.0"
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
  db:
    image: mysql:8
    container_name: db
    restart: always
    environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
volumes:
  db-data:
    driver: local
  redis-data:
    driver: local
networks:
  app-network:
    driver: bridge
